// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTmogUtbUHS5P-RanZzWn62mttEJ5PncU',
    appId: '1:879747636146:web:146d9b3d2db05af765e2ab',
    messagingSenderId: '879747636146',
    projectId: 'simpledatatracker-8f954',
    authDomain: 'simpledatatracker-8f954.firebaseapp.com',
    storageBucket: 'simpledatatracker-8f954.appspot.com',
    measurementId: 'G-8ELY0Z7FQS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVkrPfxeueCSaGmw9eIRm2_YXWRSZknAI',
    appId: '1:879747636146:android:4a6d8089a3bccdb265e2ab',
    messagingSenderId: '879747636146',
    projectId: 'simpledatatracker-8f954',
    storageBucket: 'simpledatatracker-8f954.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVNmHE_AeaNGmy36ZqrQ9ACHxPTtTTpYA',
    appId: '1:879747636146:ios:276ad35b0ac0ffd165e2ab',
    messagingSenderId: '879747636146',
    projectId: 'simpledatatracker-8f954',
    storageBucket: 'simpledatatracker-8f954.appspot.com',
    iosClientId: '879747636146-7as1gbujig47dqmc5l3t7mf28m41hqt4.apps.googleusercontent.com',
    iosBundleId: 'com.example.datatracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVNmHE_AeaNGmy36ZqrQ9ACHxPTtTTpYA',
    appId: '1:879747636146:ios:276ad35b0ac0ffd165e2ab',
    messagingSenderId: '879747636146',
    projectId: 'simpledatatracker-8f954',
    storageBucket: 'simpledatatracker-8f954.appspot.com',
    iosClientId: '879747636146-7as1gbujig47dqmc5l3t7mf28m41hqt4.apps.googleusercontent.com',
    iosBundleId: 'com.example.datatracker',
  );
}
